#!/bin/bash

docker buildx create --use
docker buildx inspect --bootstrap

docker buildx build \
  --file Dockerfile \
  --platform "linux/amd64,linux/arm64" -t "osioaliu/job-api-backend:latest" \
  --push .