#!/bin/bash
# ============================================
# Environment Initialization Script
# Generates .env file from template if missing
# ============================================

set -euo pipefail

ENV_FILE=".env"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

cd "$PROJECT_ROOT"

# Check if .env already exists
if [[ -f "$ENV_FILE" ]]; then
    echo "✓ $ENV_FILE already exists"
    echo "  To regenerate, remove the file first: rm $ENV_FILE"
    exit 0
fi

echo "Generating $ENV_FILE..."

# Generate .env file with defaults
cat << EOF > "$ENV_FILE"
# ============================================
# Docker Infrastructure Environment Variables
# Generated by scripts/init-env.sh
# ============================================

# Qdrant Configuration
QDRANT_URL=http://qdrant-db:6333

# Z.ai API Configuration
# REQUIRED: Set your Z.ai API key
ZAI_API_KEY=your_api_key_here
ZAI_BASE_URL=https://api.z.ai/v1
EOF

# Set restrictive permissions (owner read/write only)
chmod 600 "$ENV_FILE"

echo "✓ Generated $ENV_FILE"
echo ""
echo "⚠ IMPORTANT: Edit $ENV_FILE and set your ZAI_API_KEY"
echo "  Get your key from: https://z.ai/dashboard/api-keys"
echo ""
echo "  Example: ZAI_API_KEY=sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
